try containerd
The goal is to build images for multiple platforms. Here is the error
message:

  ERROR: failed to build: Multi-platform build is not supported for the docker driver.
  Switch to a different driver, or turn on the containerd image store, and try again.
  Learn more at https://docs.docker.com/go/build-multi-platform/

This is an attempt to turn on the containerd image store.